<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XMLToXHTML.xsl"?>

<!-- Filename: Spanish.xml -->
<!-- Author: Albin Engström -->

<!-- An internal DTD -->
<!DOCTYPE Dictionary [
  <!ELEMENT Dictionary (Language, Author, Words)>
  <!ELEMENT Language (#PCDATA)>
  <!ELEMENT Author (#PCDATA)>
  <!ELEMENT Words (Word+)>
  <!ELEMENT Word (#PCDATA)>
]>

<Dictionary>

	<!-- The language of the words in the dictionary -->
	<Language>Spanish</Language>

	<!-- The author of the dictionary -->
	<Author>Albin Engström</Author>

	<!-- The words in the dictionary -->
	<Words>
		<Word nr="1">Caballo</Word>
		<Word nr="2">Bola</Word>
		<Word nr="3">Casa</Word>
		<Word nr="4">Sol</Word>
		<Word nr="5">Computadora</Word>
		<Word nr="6">Agua</Word>
		<Word nr="7">Piano</Word>
		<Word nr="8">Reloj</Word>
		<Word nr="9">Auto</Word>
		<Word nr="10">Chocolate</Word>
	</Words>

</Dictionary>
